version: "3.9"
services:
  vivanov_tablenas:
    build: .
    image: vivanov/tablenas
    container_name: ${USER}_tablenas 
    ports:
      - "8899:8899"
    volumes:
      - "/mnt/:/mnt"
    shm_size: '64gb'
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
        limits:
          cpus: '4.0'
          memory: 120G
