version: "3.9"
services:
  experiments_tablenas:
    build: .
    image: experiments/tablenas
    container_name: ${USER}_tablenas 
    ports:
      - "8899:8899"
    volumes:
      - "/mnt/v/files/data:/home/data" # dataset
      - "/mnt/v/experiments/table_nas/:/home/table_nas" # lib dir 
    shm_size: '64gb'
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
        limits:
          cpus: '16.0'
          memory: 120G
